name: Docker Image CI

on:
  push:
    branches: [ "current" ]
  pull_request:
    branches: [ "current" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.glibc --tag ng-waf:0.0.1
